### PR TITLE
[124] Viewing a defect redesign

### PR DESCRIPTION
**Pull request by deberny**
## Changes in this PR:
Datetime helper outputs a time fotmatting that is user friendly

Defect details page has improved content and design, removed unnecessary content, that wasn't adding value.

Removed breadcrumbs and put a back property page link instead, as it's better to keep the breadcrumbs depth to minimum, and a defect view is a last in it's trail.

To make it easier the template structure is in one page. We will need to extract it into partials and applied to the communal defect page as well.

The content structure follows a prioritised order and is grouped by its context.

Comments are structured as list items, and have accessible content

Leaving as is, because I have to be on a different project now.

###TODO's

- Extract defect template it into partials and apply same structure to the communal defect page
- work on 'Events' section design and content
- fix tests

### Before Property defect desktop view

desktop-beforeScreenshot_2019-06-24 Defect E569F7 — Report a Defect

### After Property defect desktop view

Screenshot_2019-06-24 Defect E569F7 — Report a Defect

### Before Property defect mobile view

mobile-before-Screenshot_2019-06-24 Defect E569F7 — Report a Defect

### After Property defect mobile view

mobile_Screenshot_2019-06-24 Defect E569F7 — Report a Defect

#### Communal defect mobile view
   > needs work

### CODE REVIEW

**Comment by deberny** [comment]
[Design for defect view, create, edit](https://trello.com/c/BvdxFQr4/124-design-for-defect-view-create-edit)

**Comment by tahb** [comment]
[Time stamps that are visible to users should be in GMT not UTC](https://trello.com/c/5FE9SPKc/139-time-stamps-that-are-visible-to-users-should-be-in-gmt-not-utc)

**Comment by tahb** [comment]
I've:
- reused partials for both defect views
- styled events as best I can taking the styles from the comment block
- fixed all the failing tests
- formatted times correctly to GMT with our new shiny helper

**Comment by tahb** [comment]
Block
Screenshot 2019-06-24 at 18 43 01

Property
Screenshot 2019-06-24 at 18 43 15

**Pull request merged**
